bin_all: true
database_dir: ~/M5P_database/atlas
experiment_type: metagenomics
experimental_contrast: none
experimental_design: ~treatment
fastq_metagenomics: input_mg
fastq_metatranscriptomics: input_mt/
genome:
  find_genome_relative: false
  genome_file: reference_file
  genome_url: reference_url
mag_annotation: dram
max_memory: 1280000000000
merged_prefix: MergedReads-001
merged_reads: true
metadata_path: metadata.txt
threads: 2
working_dir: ./