#!/usr/bin/python3

#----------------------------------------------------------------------------#
#
# Microbiome Insights | Snakemake pipeline for microbial characterization
#
#----------------------------------------------------------------------------#


# Module Imports
#----------------------------------------------------------------------------#

import os, sys, re, itertools, argparse, psutil, copy, yaml, configparser
import pandas as pd
from pathlib import Path
from datetime import datetime
now = datetime.now().strftime("%d/%m/%Y %H:%M:%S")


# Configuration 
#----------------------------------------------------------------------------#
#M5P CONFIG
working_dir   = "/home/mixtures/DAVIDDEV/M5P_output"
fastq_dir     = "/home/mixtures/test_data_d1/mtg"
database_dir  = "/home/mixtures/databases/atlas/atlas"
THREADS       = 16
merged_reads  = True
merged_prefix = "MergedReads-001"
metadata_path = None
bin_all       = True

# ---- Import Snakemake rules
include: "workflows/rules/common.smk"
include: "workflows/rules/custom_atlas.smk"
include: "workflows/rules/dram_modified.smk"

# ---- Rule all: run all targets
rule all:
    input: COLLECT_ALL_INPUT()
