channels:
    bioconda
    conda-forge
dependencies:
    snakemake-minimal =5.2.4
    python =3.6 #
    jinja2 =2.10 ## Not sure if needed in the main environment
    pandas =0.24.2
    yaml
    psutil
