name: M4P CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Miniconda and create/activate the M5P environment.
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          activate-environment: M5P
          # If you have an environment file, uncomment the line below:
          # environment-file: environment.yml

      # Step 3: Install additional dependencies (e.g., those in requirements.txt).
      - name: Install additional dependencies
        shell: bash -l {0}
        run: |
          conda activate M5P
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Lint the code using flake8.
      #- name: Lint code
      #  shell: bash -l {0}
      #  run: |
      ##   pip install flake8
      #  Run flake8 on the entire repository
      #   flake8 .
      
      # Step 5: Run your test suite.
      - name: Run tests
        run: |
          conda activate M5P
          pytest

